Repository AnalogStudiosRI/www.analogstudios.net, pull requests merged in 2021-11, with the labels that each got.

#17 Spike/update home page to lit2
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .storybook/main.js
  .storybook/preview.js
  greenwood.config.js
  package.json
  postcss.config.js
  src/assets/home-banner.jpg
  src/components/events-calendar/events-calendar.css
  src/components/events-calendar/events-calendar.js
  src/components/footer/footer.css
  src/components/footer/footer.js
  src/components/footer/footer.spec.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/header.spec.js
  src/components/navigation/navigation.css
  src/components/navigation/navigation.js
  src/components/posts-list/posts-list.css
  src/components/posts-list/posts-list.js
  src/index.html
  src/index.js
  src/routes/home.css
  src/routes/home.js
  src/services/events-service.js
  src/services/posts-service.js
  src/styles.css
  src/theme.css
  web-test-runner.config.js
  yarn.lock
Labels: enhancement

#19 Spike/upgrade all top "level" pages lit2
  greenwood.config.js
  src/components/card/card.css
  src/components/card/card.js
  src/components/events-calendar/events-calendar.js
  src/index.html
  src/index.js
  src/routes/albums/album-details.js
  src/routes/albums/albums.css
  src/routes/albums/albums.js
  src/routes/artists/artist-details.js
  src/routes/artists/artists.css
  src/routes/artists/artists.js
  src/routes/events/event-details.js
  src/routes/events/events.css
  src/routes/events/events.js
  src/routes/home/home.css
  src/routes/home/home.js
  src/services/albums-service.js
  src/services/artists-service.js
  src/store.js
  src/styles.css
  src/theme.css
Labels: enhancement

#30 adopt published version of font awesome greenwood plugin
  greenwood.config.js
  package.json
  yarn.lock
Labels: chore

#34 hide inactive artists from artists servivce response
  src/services/artists-service.js
Labels: feature

#36 artists page relevancy enhancements
  src/components/card/card.js
  src/routes/artists/artists.js
Labels: feature

#40 fix spacing and styles on homepage banner
  src/routes/home/home.css
Labels: bug, bounty:claimed

#38 Details Pages
  src/routes/albums/album-details.js
  src/routes/albums/albums.css
  src/routes/artists/artist-details.js
  src/routes/events/event-details.js
  src/routes/events/events.css
  src/services/albums-service.js
  src/services/events-service.js
Labels: feature, bounty:eligible

#44 remove duplicate events route in router definitions
  src/index.js
Labels: chore

#46 fix meta description
  src/index.html
Labels: chore

#47 fix header styles
  src/components/header/header.css
  src/components/header/header.js
  src/components/navigation/navigation.css
  src/index.html
Labels: bug

#49 fix events page styling
  src/routes/events/event-details.js
  src/routes/events/events.css
  src/routes/events/events.js
Labels: bug, bounty:claimed

#48 fix homepage landing styles
  src/components/header/header.css
  src/components/navigation/navigation.css
  src/routes/home/home.css
  src/routes/home/home.js
Labels: bug, bounty:claimed
