Repository AnalogStudiosRI/www.analogstudios.net, pull requests merged in 2021-12, with the labels that each got.

#6 migrate (back) to TypeScript
  .eslintrc.js
  greenwood.config.js
  netlify.toml
  package.json
  src/components/card/card.model.ts
  src/components/card/card.ts
  src/components/events-calendar/events-calendar.ts
  src/components/footer/footer.js
  src/components/footer/footer.spec.js
  src/components/footer/footer.ts
  src/components/header/header.js
  src/components/header/header.spec.js
  src/components/header/header.ts
  src/components/navigation/navigation.ts
  src/components/posts-list/posts-list.ts
  src/index.html
  src/index.ts
  src/routes/albums/album-details.ts
  src/routes/albums/albums.ts
  src/routes/artists/artist-details.ts
  src/routes/artists/artists.ts
  src/routes/events/event-details.ts
  src/routes/events/events.js
  src/routes/events/events.ts
  src/routes/home/home.ts
  src/services/albums/album.model.ts
  src/services/albums/albums-service.ts
  src/services/artists/artist.model.ts
  src/services/artists/artists-service.ts
  src/services/events/event.model.ts
  src/services/events/events-service.ts
  src/services/posts-service.js
  src/services/posts/post.model.ts
  src/services/posts/posts-service.ts
  src/store.ts
  src/typings.d.ts
  tsconfig.json
  web-test-runner.config.js
  yarn.lock
Labels: chore

#52 initial implementation of netlify form
  src/index.html
  src/index.ts
  src/routes/contact/contact.css
  src/routes/contact/contact.ts
Labels: feature

#58 improve setup docs for nodejs min version and support nvm
  .github/CONTRIBUTING.md
  .nvmrc
  README.md
  package.json
Labels: chore

#53 upgrade to v0.20.0-alpha.0 and node 14
  .eslintrc.cjs
  greenwood.config.js
  package.json
  postcss.config.cjs
  postcss.config.mjs
  stylelint.config.cjs
  web-test-runner.config.js
  yarn.lock
Labels: chore

#59 remove hard limit on viewable calendar tiles
  src/components/events-calendar/events-calendar.ts
Labels: bug

#54 restoring social share
  greenwood.config.js
  package.json
  src/components/social-share/social-share.css
  src/components/social-share/social-share.ts
  src/routes/albums/album-details.ts
  src/routes/artists/artist-details.ts
  src/routes/events/event-details.ts
  src/routes/events/events.css
  yarn.lock
Labels: feature
