Repository AnalogStudiosRI/www.analogstudios.net, pull requests merged in 2022-01, with the labels that each got.

#62 solid page content background and some padding for content
  src/styles.css
Labels: bug

#66 upgrade to latest greenwood
  package.json
  yarn.lock
Labels: chore

#65 apply best practices, SEO, and a11y Lighthouse feedback to achieve all 100s
  src/components/card/card.ts
  src/components/events-calendar/events-calendar.ts
  src/components/navigation/navigation.css
  src/components/navigation/navigation.ts
  src/favicon.ico
  src/index.html
  src/robots.txt
  src/routes/albums/album-details.ts
  src/routes/home/home.ts
Labels: chore, needs upstream

#64 Feature/footer social media icons - option 2
  src/components/footer/footer.css
  src/components/footer/footer.spec.js
  src/components/footer/footer.ts
Labels: feature

#63 restore basic GA integration
  greenwood.config.js
  package.json
  src/routes/albums/album-details.ts
  src/routes/albums/albums.ts
  src/routes/artists/artist-details.ts
  src/routes/artists/artists.ts
  src/routes/contact/contact.ts
  src/routes/events/event-details.ts
  src/routes/events/events.ts
  src/routes/home/home.ts
  yarn.lock
Labels: chore

#68 apply CSS and image lighthouse perf recommendations
  .gitattributes
  greenwood.config.js
  src/assets/home-banner.jpg
  src/assets/home-banner.webp
  src/assets/view-banner.png
  src/assets/view-banner.webp
  src/components/footer/footer.ts
  src/index.html
  src/routes/home/home.ts
  src/styles.css
Labels: chore

#69 constrain contact form for mobile
  src/routes/contact/contact.css
Labels: bug

#70 Chore/aws release uploader
  .github/workflows/main.yml
  deploy.js
  package.json
  yarn.lock
Labels: chore
